### PR TITLE
Making the categories work with RO and RP-1

### PR DESCRIPTION
**Pull request by Gordon-Dry**
-      Procedural Avionics appears in Procedural Parts category
-     "SRBs" also lists parts with HTPB, PBAN and PSPC
-     "Rockets" also lists parts with Kerosene/LqdOxygen and HTP/Kerosene/LqdOxygen
-     Added subcategory "Sounding Rockets" for the fuel combo Aniline/Furfuryl/IRFNA-III
-     Added subcategory "Early Rockets" for the fuel combos Ethanol75/LqdOxygen | Ethanol75/HTP/LqdOxygen | Ethanol90/HTP/LqdOxygen | Hydyne/HTP/LqdOxygen | AK20/Kerosene
-     Added subcategory "Upper Stage Engines" for the fuel combos IWFNA/UDMH | HTP/Kerosene
-     Added subcategory "GPS" to science in favor of KerbalGPS
-     Repaired appearance in Science category

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
I should not use # and a number in comments here...

At least I should add a blank space inbetween.

**Comment by Gordon-Dry** [comment]
On hold.
FE is not able to have several lines like this:
```
	name = HTPB=>SRBs
	name = PBAN=>SRBs
	name = PSPC=>SRBs

```
It will only accept the first line.

How to avoid this, @linuxgurugamer ?

**Comment by Gordon-Dry** [comment]
Where exactly does FE look for the fuel types in an engine?
Besides RESOURCE ofc.
Does it look into ModuleEngines*/PROPELLANT ?
And if that one is empty, does it look into ModuleEngineConfigs,*/CONFIG/ and there the default config? Either the only one or the default one defined by "configuration =" in ModuleEngineConfigs root?
I guess the last variant it does not, so many engines cannot be listed properly.

Even in "Engines/All parts in engines" some parts are not listed, like the "Castor 1" which does not have ModuleEnginesRF/PROPELLANT but ModuleEngineConfigs. And stock RESOURCE is removed.

Excerpt of that part's relevant entries of MM cache:
```
		MODULE
		{
			name = ModuleEnginesRF
			thrustVectorTransformName = thrustTransform
			EngineType = SolidBooster
			allowShutdown = False
			throttleLocked = True
			exhaustDamage = True
			maxThrust = 304.3
			RFConfig = TRUE
			shieldedCanActivate = True
			exhaustDamageMultiplier = 20
			exhaustDamageFalloffPower = 1
			exhaustDamageMaxMutliplier = 1.0
			exhaustDamageSplashbackMult = 0.1
			exhaustDamageSplashbackMaxMutliplier = 0.1
			stagingEnableText = Engine: Enable Staging
			stagingDisableText = Engine: Disable Staging
			stagingToggleEnabledEditor = true
		}
```
and
```
		MODULE
		{
			name = ModuleEngineConfigs
			configuration = XM-20
			modded = false
			origMass = 0.651
			type = ModuleEnginesRF
			CONFIG
			{
				name = XM-20
				minThrust = 304.3
				maxThrust = 304.3
				heatProduction = 100
				curveResource = PSPC
				chamberNominalTemp = 1500
				maxEngineTemp = 2040
				techRequired = solids1956
				cost = 0
				description = The XM-20 Sergeant was a Castor predecessor that was used on the X-17 hypersonic test vehicle.
				powerEffectName = Solid-Lower
				PROPELLANT
				{
					name = PSPC
					ratio = 1.0
					DrawGauge = True
				}
				atmosphereCurve
				{
					key = 0 214.5
					key = 1 191
				}
				thrustCurve
				{
					key = 1.00000 1.00000   3.04530   0.00000
					key = 0.98041 0.93846   3.24502   3.24479
					key = 0.96207 0.87692   1.95348   3.47247
					key = 0.92803 0.80769   0.70693   2.12062
					key = 0.89585 0.78462  -0.01964   0.72771
					key = 0.63391 0.78974  -0.01951  -0.01951
					key = 0.37025 0.79487  -0.01939  -0.01939
					key = 0.10490 0.80000   4.75933  -0.01926
					key = 0.08614 0.70513   5.40035   5.39697
					key = 0.06975 0.61026   6.24129   6.23522
					key = 0.05572 0.51538   7.39346   7.38134
					key = 0.04406 0.42051   9.07067   9.04263
					key = 0.03476 0.32564  11.74722  11.66525
					key = 0.02783 0.23077   5.33132  16.41311
					key = 0.01926 0.17949   6.87286   6.82783
					key = 0.01283 0.12821   9.72732   9.53333
					key = 0.00855 0.07692   4.53459  15.71336
					key = 0.00380 0.05128   6.99782   6.69392
					key = 0.00095 0.02564  12.41023  12.99596
					key = 0.00000 0.01000   0.00000  26.86142
				}
			}
			CONFIG
			{
				name = Castor-1-SL
				minThrust = 324.6
				maxThrust = 324.6
				heatProduction = 100
				curveResource = PSPC
				chamberNominalTemp = 1500
				maxEngineTemp = 2040
				techRequired = solids1958
				cost = 0
				description = Sea level optimized variant of the Castor 1 SRM.
				powerEffectName = Solid-Lower
				PROPELLANT
				{
					name = PSPC
					ratio = 1.0
					DrawGauge = True
				}
				atmosphereCurve
				{
					key = 0 247
					key = 1 220
				}
				thrustCurve
				{
					key = 1.00000 1.00000   3.04530   0.00000
					key = 0.98041 0.93846   3.24502   3.24479
					key = 0.96207 0.87692   1.95348   3.47247
					key = 0.92803 0.80769   0.70693   2.12062
					key = 0.89585 0.78462  -0.01964   0.72771
					key = 0.63391 0.78974  -0.01951  -0.01951
					key = 0.37025 0.79487  -0.01939  -0.01939
					key = 0.10490 0.80000   4.75933  -0.01926
					key = 0.08614 0.70513   5.40035   5.39697
					key = 0.06975 0.61026   6.24129   6.23522
					key = 0.05572 0.51538   7.39346   7.38134
					key = 0.04406 0.42051   9.07067   9.04263
					key = 0.03476 0.32564  11.74722  11.66525
					key = 0.02783 0.23077   5.33132  16.41311
					key = 0.01926 0.17949   6.87286   6.82783
					key = 0.01283 0.12821   9.72732   9.53333
					key = 0.00855 0.07692   4.53459  15.71336
					key = 0.00380 0.05128   6.99782   6.69392
					key = 0.00095 0.02564  12.41023  12.99596
					key = 0.00000 0.01000   0.00000  26.86142
				}
			}
			CONFIG
			{
				name = Castor-1-Vac
				minThrust = 349.3
				maxThrust = 349.3
				heatProduction = 100
				curveResource = PSPC
				chamberNominalTemp = 1500
				maxEngineTemp = 2040
				techRequired = solids1958
				cost = 0
				description = Vacuum optimized variant of the Castor 1 SRM.
				powerEffectName = Solid-Lower
				PROPELLANT
				{
					name = PSPC
					ratio = 1.0
					DrawGauge = True
				}
				atmosphereCurve
				{
					key = 0 273.21
					key = 1 200
				}
				thrustCurve
				{
					key = 1.00000 1.00000   3.04530   0.00000
					key = 0.98041 0.93846   3.24502   3.24479
					key = 0.96207 0.87692   1.95348   3.47247
					key = 0.92803 0.80769   0.70693   2.12062
					key = 0.89585 0.78462  -0.01964   0.72771
					key = 0.63391 0.78974  -0.01951  -0.01951
					key = 0.37025 0.79487  -0.01939  -0.01939
					key = 0.10490 0.80000   4.75933  -0.01926
					key = 0.08614 0.70513   5.40035   5.39697
					key = 0.06975 0.61026   6.24129   6.23522
					key = 0.05572 0.51538   7.39346   7.38134
					key = 0.04406 0.42051   9.07067   9.04263
					key = 0.03476 0.32564  11.74722  11.66525
					key = 0.02783 0.23077   5.33132  16.41311
					key = 0.01926 0.17949   6.87286   6.82783
					key = 0.01283 0.12821   9.72732   9.53333
					key = 0.00855 0.07692   4.53459  15.71336
					key = 0.00380 0.05128   6.99782   6.69392
					key = 0.00095 0.02564  12.41023  12.99596
					key = 0.00000 0.01000   0.00000  26.86142
				}
			}
		}
```

**Comment by linuxgurugamer** [comment]
There are conflicts, can you resolve them and commit the changes, please

**Comment by aradapilot** [comment]
would love to see this revisited

**Comment by linuxgurugamer** [comment]
@Gordon-Dry Can you fix the conflicts, please

**Comment by linuxgurugamer** [comment]
I'm planning on doing a release Sunday evening, if this isn't fixed by then it won't be included

**Comment by Gordon-Dry** [comment]
Done

**Comment by linuxgurugamer** [comment]
Thank you

**Pull request merged**
