### PR TITLE
Add crewed pods

### PR DESCRIPTION
**Pull request by Gordon-Dry**
Until now only the probes were patched.

Now also crewed pods get part upgrades:
advUnmanned: Crewable pods now have a basic embedded transmission antenna.
heavyCommandModules: Crewable pods are now remote controllable (for unmanned testing).

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
Wait until I say "GO"

**Comment by linuxgurugamer** [comment]
Still waiting for the "GO"

**Comment by Gordon-Dry** [comment]
Technically it's okay now, but it seems that RT modules are not capable of understanding
moduleIsEnabled = false
moduleIsEnabled = true

so the modules are enabled from start.

I checked the MM cache, I checked the context menus of R&D, I checked in VAB and ingame ...

I will let it be like this - because it does not make the game stop working and it is correct now - somehow.

I opened an issue on the RT repo:
https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/763

It COULD be that the Kerbalism planner - which does not take the state of moduleIsEnabled into account - could be the culprit (as well) - but the planner is "only" for showing and toggling the reliability quality of a part and the EC in/out ... somehow.
So why SHOULD it be the culprit - it could ...
Issue, too:
https://github.com/steamp0rt/Kerbalism/issues/215

So I give it a GO whatsoever ...

**Comment by Gordon-Dry** [comment]
It's final now. Because it worked without any issues.

And because of

Quote KSP-TaxiService:
"No, it is not possible to have both ModuleRTAntenna and ModuleRTAntennaPassive siding in one same part.
ModuleRTAntennaPassive is intended for non-antenna parts like probe core while ModuleRTAntenna is for antenna-type parts."

Green light for real.

**Comment by linuxgurugamer** [comment]
Next time, if you are continuing to work on a patch, pull it until it is ready

**Pull request merged**
